### ISSUE TITLE
При компиляции скетча выдаёт ошибку 'class GyverPortal' has no member named 'copyCheck'    esp8266

### ISSUE THREAD

**Issue by ATLASO4EK** [AlexGyver/SunTracker#1]
Полная ошибка:
SunTracker-main\firmware\SunTracker\actions.ino: In function 'void action()':
actions:41:12: error: 'class GyverPortal' has no member named 'copyCheck'
   41 |     if (ui.copyCheck("spdOn", spdOn)) {
      |            ^~~~~~~~~
actions:56:12: error: 'class GyverPortal' has no member named 'copyCheck'
   56 |     if (ui.copyCheck("planOn", planOn)) {
      |            ^~~~~~~~~
actions:66:8: error: 'class GyverPortal' has no member named 'copyCheck'
   66 |     ui.copyCheck("track", data.track);
      |        ^~~~~~~~~
exit status 1
'class GyverPortal' has no member named 'copyCheck'

Посмотрел документацию на GyverPortal и там не оказалось никакого такого copyCheck

**Comment by GyverLibs** [comment]
проект написан на старой версии GyverPortal
